title: 'Visual Media'
since: '2022-10-16'
content: 'Projects that showcase my photography and video production skills.'
updated_by: 25de984e-075a-47a8-8b41-32e9880eb240
updated_at: 1665978708
blueprint: skills
