title: 'Visual Media'
since: '2012-01-01'
content: 'Projects that showcase my photography and video production skills.'
updated_by: 6ab68b5f-4613-467b-99de-86fabe1e1bcd
updated_at: 1670972877
blueprint: skills
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
meta_title: 'All Visual Media Projects // Aidan Weltner'
