title: WordPress
content: 'WordPress development and consulting'
updated_by: 6ab68b5f-4613-467b-99de-86fabe1e1bcd
updated_at: 1670972893
blueprint: skills
since: '2015-05-01'
meta_title: 'All WordPress Projects // Aidan Weltner'
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
