title: Archived
marker: bg-red-500
updated_by: 6ab68b5f-4613-467b-99de-86fabe1e1bcd
updated_at: 1670972802
blueprint: project_status
order: 3
meta_title: 'All Archived Projects // Aidan Weltner'
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
