title: Creative
updated_by: 6ab68b5f-4613-467b-99de-86fabe1e1bcd
updated_at: 1670720584
blueprint: categories
content: 'Bite-sized creative tests, experiments, daily challenges, warm ups, or other small tidbits worth sharing. Could be code, photography, design, or a variety of different mediums.'
meta_title: 'Creative // Aidan Weltner'
meta_description: 'Bite-sized creative tests, experiments, daily challenges, warm ups, or other small tidbits worth sharing. Could be code, photography, design, or a variety of different mediums.'
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
