title: Moments
updated_by: 25de984e-075a-47a8-8b41-32e9880eb240
updated_at: 1653339843
blueprint: categories
content: 'A place for milestones, personal achievements, changes, updates, or other adventures worth sharing. Shout out to [Rob Hope](https://robhope.com/moments) for the idea.'
